### ISSUE TITLE
Snap support

### ISSUE THREAD

**Issue by tvsfx** [rose-pine/gtk#48]
Would you be open to supporting a snap package of this theme? I wanted to use this theme in my firefox/thunderbird snaps, so I went ahead and hacked together a quick snap that does the job on my end. I solely use `rose-pine-moon`, so that's what I packaged for now.

I followed the structure of the [gtk-common-themes](https://github.com/ubuntu/gtk-common-themes/blob/main/snap/snapcraft.yaml) snap.

<details>
  <summary>Manifest for rose pine moon snap</summary>

```yaml
name: rose-pine-moon
version: '1.0'
summary: Rose pine moon but snapified
description: Took inspiration from the gtk-common-themese template and used this to snapify rose-pine-moon

# We build against Ubuntu 24.04 packages, but use the "bare" base as
# we don't want to force installation of a large base snap.
build-base: core24
base: bare
compression: lzo

grade: stable
confinement: strict

slots:
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/rose-pine-moon
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/rose-pine-moon


parts:
  themes:
    plugin: dump
    source: ./themes/rose-pine-moon/
    organize:
      '*': share/themes/rose-pine-moon/
  icons:
    plugin: dump
    source: ./icons/rose-pine-moon/
    organize:
      '*': share/icons/rose-pine-moon/

```
</details>

Then with the following file structure (the `rose-pine-moon` folder is just taken from this repo, with the caveat that if you take the `icons` release there's some unresolved symbolic links that `snapcraft` gets mad over, so I had to copy the folder from sources directly ):
```
├── icons
│   └── rose-pine-moon
├── snapcraft.yaml
└── themes
    └── rose-pine-moon
```

You just build the snap and then run
```sh
for i in $(snap connections | grep gtk-common-themes:gtk-3-themes | awk '{print $2}'); do sudo snap connect $i rose-pine-moon:gtk-3-themes; done
for i in $(snap connections | grep gtk-common-themes:icon-themes | awk '{print $2}'); do sudo snap connect $i rose-pine-moon:icon-themes; done
```

Now running `GTK_THEME=rose-pine-moon firefox` does the job.
